//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Game
{
    private bool gameIsWon = false;

	public virtual InputView InputView
	{
		get;
		set;
	}
    public Game()
    {
        gameIsWon = false;
    }

	public virtual void StartGame()
	{
        Console.Clear();
        Console.WriteLine("┌────────────────────────────────────────────────────┐");
        Console.WriteLine("| Welkom bij Sokoban                                 |");
        Console.WriteLine("|                                                    |");
        Console.WriteLine("| betekenis van de symbolen   |   doel van het spel  |");
        Console.WriteLine("|                             |                      |");
        Console.WriteLine("| spatie : outerspace         |   duw met de truck   |");
        Console.WriteLine("|      █ : muur               |   de krat(ten)       |");
        Console.WriteLine("|      · : vloer              |   naar de bestemming |");
        Console.WriteLine("|      O : krat               |                      |");
        Console.WriteLine("|      0 : krat op bestemming |                      |");
        Console.WriteLine("|      x : bestemming         |                      |");
        Console.WriteLine("|      @ : truck              |                      |");
        Console.WriteLine("|  WASD  : beweging           |                      |");
        Console.WriteLine("└────────────────────────────────────────────────────┘");
        Console.WriteLine("Press enter to continoue");
        PlayTheGame();
	}

	public virtual void CheckIfWon()
	{
		
	}

    public void PlayTheGame()
    {
        while (!gameIsWon)
        {

        }
    }

}

