//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class InputView
{
	public virtual Game Game
	{
		get;
		set;
	}

	public virtual Level Level
	{
		get;
		set;
	}

	public string Inputhandeler(String input)
	{
        switch (input.ToUpper())
        {
            case "W":
                // go up
                return "W";
            case "A":
                // go left
                return "A";
            case "S":
                // go down
                return "S";
            case "D":
                // go right
                return "D";
            case "R":
                // go right
                return "R";
        }
        return null;
	}

}

