using ConsoleApplication1.generatedcode;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Level
{
    private string name
    {
        get;
        set;
    }

	private int xSize
	{
		get;
		set;
	}

	private int ySize
	{
		get;
		set;
	}

	public Item[,] playingField;

    InputView iv;
    Truck truck;

	public virtual OutputView OutputView
	{
		get;
		set;
	}
    public Level(int levelSize)
    {
        xSize = levelSize;
        ySize = levelSize;
        playingField = new Item[levelSize, levelSize];
        iv = new InputView();
        truck = new Truck();

        for(int index = 0; index < playingField.GetLength(0); index++)
        {
            for (int indey = 0; indey < playingField.GetLength(1); indey++)
            {
                Field f = new Field("." + index + "," + indey);
                playingField[index, indey] = f;
            }
        }
    }
    public void UpdateField()
    {
        // loop door dubbele array 
        for (int j = 0; j < xSize; j++)
        {
            for (int i = 0; i < ySize; i++)
            {
                if (playingField[j,i] != null)
                {
                    if(playingField[j,i].GetType() == typeof(Field))
                    {
                        Field temp = (Field)playingField[j,i];
                        temp.DeterminName();
                    }

                    playingField[j,i].PrintName();
                    if (i == ySize - 1)
                    {
                        Console.WriteLine("");
                    }
                }
               
            }
        }
    }

    public void MoveTruck(string _key)
    {
        switch (_key.ToString().ToUpper())
        {
            case "D":
                truck.MoveRight();
                break;
            case "S":
                truck.MoveDown();
                break;
            case "A":
                truck.Moveleft();
                break;
            case "W":
                truck.MoveUp();
                break;
        }
    }
}

