//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

public class levelmanager
{
	private List<String> levelList
	{
		get;
		set;
	}

	public virtual IEnumerable<Level> Level
	{
		get;
		set;
	}

	public virtual List<String> GetLevelList()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Addlevel(Level level)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Getlevel(string levelName)
	{
        throw new System.NotImplementedException();
	}

	public virtual void RemoveLevel(Level level)
	{
		throw new System.NotImplementedException();
	}

	private void ReadFile()
	{
		
	}

	public virtual void SetFields()
	{
		throw new System.NotImplementedException();
	}
    private void reader()
    {

    }

}

