//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Program
{


    static void Main(string[] args)
    {
       // Game game = new Game();
        //game.StartGame();
        //Console.ReadLine();
        levelmanager a = new levelmanager();
        a.ReadFile(1);
    }
}

