//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Field
{
	private int xPosition
	{
		get;
		set;
	}

	private int yPosition
	{
		get;
		set;
	}

	private bool isWall
	{
		get;
		set;
	}

    private bool isBox
	{
		get;
		set;
	}

    private bool isTruck
	{
		get;
		set;
	}

    private bool isTarget
	{
		get;
		set;
	}

    private bool isFilledTarget
	{
		get;
		set;
	}

	public virtual Type Field_type
	{
		get;
		set;
	}

	public virtual Level Level
	{
		get;
		set;
	}

}

