//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Game
{
	public virtual Program Program
	{
		get;
		set;
	}

	public virtual InputView InputView
	{
		get;
		set;
	}

	public virtual void StartGame()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CheckIfWon()
	{
		throw new System.NotImplementedException();
	}

}

