//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class InputView
{
	public virtual Game Game
	{
		get;
		set;
	}

	public virtual Level Level
	{
		get;
		set;
	}

	public virtual void Inputhandeler(String input)
	{
        if(input.Length > 1)
        { 
            Console.WriteLine("Please type only 1 letter a time");
            Console.ReadLine();
        }
        switch (input.ToUpper())
        {
            case "W":
                // go up
                break;
            case "A":
                // go left
                break;
            case "S":
                // go down
                break;
            case "D":
                // go right
                break;
        }
	}

}

