//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Level
{
	private string name
	{
		get;
		set;
	}

	private int xSize
	{
		get;
		set;
	}

	private int ySize
	{
		get;
		set;
	}

	private Field[][] Fields
	{
		get;
		set;
	}

	public virtual IEnumerable<Field> Field
	{
		get;
		set;
	}

	public virtual InputView Controller
	{
		get;
		set;
	}

	public virtual levelmanager levelmanager
	{
		get;
		set;
	}

	public virtual OutputView OutputView
	{
		get;
		set;
	}

	public virtual void MoveDown()
	{
		throw new System.NotImplementedException();
	}

	public virtual void MoveUp()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Moveleft()
	{
		throw new System.NotImplementedException();
	}

	public virtual void MoveRight()
	{
		throw new System.NotImplementedException();
	}
}

